# Generated by Django 5.1 on 2024-10-19 08:06

import django.db.models.deletion
import job_seekers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_no', models.BigIntegerField(max_length=15, validators=[job_seekers.models.validate_phone_number])),
                ('Addres', models.TextField()),
                ('career_obj', models.TextField()),
                ('profile_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LanguageName', models.CharField(max_length=40)),
                ('Proficiency', models.CharField(choices=[('biggner', 'biggner'), ('intermediat', 'intermediat'), ('advance', 'advance'), ('fluent', 'fluent')], max_length=40)),
                ('Can_Read', models.BooleanField(default=False)),
                ('Can_Speak', models.BooleanField(default=False)),
                ('Can_Write', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seekers.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(choices=[('B.tech', 'B.tech'), ('M.tech', 'M.tech')], max_length=40)),
                ('Institute_name', models.CharField(max_length=40)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seekers.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(choices=[('software engineering', 'software engineering'), ('markating manager', 'markating manager'), ('coustomer service', 'coustomer service')], max_length=40)),
                ('Project_name', models.TextField(max_length=100)),
                ('Company_name', models.CharField(max_length=40)),
                ('Technology', models.CharField(max_length=40)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seekers.personalinfo')),
            ],
        ),
    ]
