# Generated by Django 5.1 on 2024-10-19 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_name', models.CharField(max_length=40)),
                ('Proficiency', models.CharField(choices=[('biggner', 'biggner'), ('intermediat', 'intermediat'), ('advance', 'advance'), ('Expart', 'Expart')], max_length=40)),
                ('Year_of_Experiance', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seekers.personalinfo')),
            ],
        ),
    ]
