# Generated by Django 5.1 on 2024-10-19 08:28

import job_seekers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0003_alter_personalinfo_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='Phone_no',
            field=models.CharField(max_length=15, validators=[job_seekers.models.validate_phone_number]),
        ),
    ]
