# Generated by Django 5.1 on 2024-10-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0004_alter_personalinfo_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='career_obj',
            field=models.TextField(null=True),
        ),
    ]
