# Generated by Django 5.1 on 2024-10-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0006_skill_delete_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='Proficiency',
            field=models.CharField(choices=[('biggner', 'biggner'), ('intermediat', 'intermediat'), ('advance', 'advance')], max_length=40),
        ),
    ]
