# Generated by Django 5.1 on 2024-10-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seekers', '0008_personalinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Skill_name',
            new_name='Skillname',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='Year_of_Experiance',
            new_name='YearofExperiance',
        ),
    ]
