# Generated by Django 5.1 on 2024-10-24 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employeers', '0001_initial'),
        ('job_seekers', '0009_rename_skill_name_skill_skillname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employeers.jobpost')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seekers.personalinfo')),
            ],
        ),
    ]
