# Generated by Django 5.1 on 2024-10-24 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employeers', '0001_initial'),
        ('job_seekers', '0010_applicants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicants',
            new_name='Applicant',
        ),
    ]
